version: '3.8'

services:
  postgresDb:
    container_name: DragoDeskHelpDb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: DragoDeskHelpDb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d DragoDeskHelpDb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgresql_data: